# Generated by Django 3.2.3 on 2021-07-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivosmaterias',
            fields=[
                ('materia', models.IntegerField(primary_key=True, serialize=False)),
                ('presentacion', models.FileField(blank=True, null=True, upload_to='fmaterias/presentaciones')),
                ('bloque1', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque2', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque3', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque4', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque5', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque6', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque7', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque8', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque9', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('bloque10', models.FileField(blank=True, null=True, upload_to='fmaterias/bloques')),
                ('foroact1', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact2', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact3', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact4', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact5', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact6', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact7', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact8', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact9', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('foroact10', models.FileField(blank=True, null=True, upload_to='fmaterias/actyforos')),
                ('examen1', models.FileField(blank=True, null=True, upload_to='fmaterias/examenes')),
                ('examen2', models.FileField(blank=True, null=True, upload_to='fmaterias/examenes')),
                ('examen3', models.FileField(blank=True, null=True, upload_to='fmaterias/examenes')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrograma', models.CharField(max_length=50)),
                ('numPeriodos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMateria', models.CharField(max_length=80)),
                ('numPeriodo', models.IntegerField()),
                ('idPrograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.programa')),
            ],
        ),
    ]
